Repository Doer-org/glyph, pull requests merged in 2023-04, with the labels that each got.

#23 Feat(client): api clientを追加
  client/package.json
  client/pnpm-lock.yaml
  client/src/api/core/api-client.ts
  client/src/api/core/index.ts
  client/src/api/core/types/glyph.ts
  client/src/api/core/types/health.ts
  client/src/api/core/types/index.ts
  client/src/api/core/types/result.ts
  client/src/api/core/types/user.ts
  client/src/api/glyph.ts
  client/src/api/health.ts
  client/src/api/index.ts
  client/src/api/user.ts
Labels: 🚧 wip

#28 Client/feat/api client
  client/next.config.js
  client/package.json
  client/pnpm-lock.yaml
  client/src/api/core/api-client.ts
  client/src/api/core/types/glyph.ts
  client/src/api/core/types/index.ts
  client/src/api/core/types/user.ts
  client/src/api/glyph.ts
  client/src/api/glyph/__test__/glyph-api.test.ts
  client/src/api/glyph/index.ts
  client/src/api/glyph/types/index.ts
  client/src/api/health/__test__/health.test.ts
  client/src/api/health/index.ts
  client/src/api/health/types/index.ts
  client/src/api/index.ts
  client/src/api/user.ts
  client/src/api/user/__test__/user.test.ts
  client/src/api/user/index.ts
  client/src/api/user/types/index.ts
  client/test/setup.ts
  client/tsconfig.json
  client/vitest.config.ts
Labels: 🚧 wip

#29 Client/fix/api client
  client/src/api/core/api-client.ts
  client/src/api/glyph/__test__/glyph-api.test.ts
  client/src/api/glyph/index.ts
  client/src/api/glyph/types/index.ts
  client/src/api/user/__test__/user.test.ts
  client/src/api/user/index.ts
  client/src/api/user/types/index.ts
Labels: 🚧 wip

#36 Server auto-merge depandabot
  .github/workflows/dependabot-auto-merge.yml
Labels: ci

#39 Client/feat/api client
  client/src/api/comments/__test__/comments.test.ts
  client/src/api/comments/index.ts
  client/src/api/comments/types/index.ts
  client/src/api/core/api-client.ts
  client/src/api/glyph/__test__/glyph-api.test.ts
  client/src/api/glyph/index.ts
  client/src/api/glyph/types/index.ts
  client/src/components/organisms/glyphs/glyphCreateForm/index.tsx
Labels: 🚧 wip

#77 ciのディレクトリを適切なものに変更する
  .github/workflows/client-build-check.yaml
  .github/workflows/go.yml
Labels: ci

#75 Client/refactor/auth
  client/src/api/auth/index.ts
  client/src/api/auth/types/index.ts
  client/src/api/auth/user.ts
  client/src/api/index.ts
  client/src/app/page.tsx
  client/src/app/service/comments/page.tsx
  client/src/app/service/glyphs/[glyph_id]/page.tsx
  client/src/app/service/layout.tsx
  client/src/features/auth/components/auth.tsx
  client/src/features/auth/index.ts
  client/src/features/auth/utils/get-token.tsx
  client/src/features/index.ts
  client/src/middleware.ts
Labels: client
