Repository Doer-org/glyph, pull requests merged in 2023-05, with the labels that each got.

#90 ci: visual regression testを導入
  .github/workflows/reg.yaml
  client/.eslintrc.json
  client/.gitignore
  client/.storybook/main.ts
  client/.storybook/preview.ts
  client/package.json
  client/pnpm-lock.yaml
  client/regconfig.json
  client/src/stories/Button.stories.ts
  client/src/stories/Button.tsx
  client/src/stories/Header.stories.ts
  client/src/stories/Header.tsx
  client/src/stories/Introduction.mdx
  client/src/stories/Page.stories.ts
  client/src/stories/Page.tsx
  client/src/stories/assets/code-brackets.svg
  client/src/stories/assets/colors.svg
  client/src/stories/assets/comments.svg
  client/src/stories/assets/direction.svg
  client/src/stories/assets/flow.svg
  client/src/stories/assets/plugin.svg
  client/src/stories/assets/repo.svg
  client/src/stories/assets/stackalt.svg
  client/src/stories/button.css
  client/src/stories/header.css
  client/src/stories/page.css
Labels: 🚧 wip, client

#88 CI/ golang-ci-lintをgithub actions に追加する
  .github/workflows/golangci-lint.yml
  server/.go-version
  server/go.mod
  server/go.sum
Labels: ci

#96 ci/usesでもう一度できるか見てみる
  .github/workflows/golangci-lint.yml
Labels: ci

#98 CI/dependabot なら reg-ci をrunさせない
  .github/workflows/reg.yaml
Labels: ci

#107 CI/test で db の立ち上げを行う
  .github/workflows/go.yml
  server/.env.db.sample
  server/Makefile
  server/docker/docker-compose.ci.database.yml
  server/docker/docker-compose.ci.yml
Labels: ci

#101 server/user-test作成
  server/go.mod
  server/go.sum
  server/internal/domain/mock_repository/user.go
  server/internal/infrastructure/persistance/user.go
  server/internal/usecase/user.go
  server/internal/usecase/user_test.go
Labels: server

#109 Server/table schema を migrationに変更
  server/cmd/migrate/Dockerfile
  server/cmd/migrate/main.go
  server/cmd/serve.go
  server/dbconfig.yml
  server/docker/docker-compose.local.database.yml
  server/go.mod
  server/go.sum
  server/migrations/20230524001810-create_table.sql
Labels: server
